version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend-service
    networks:
      - app-network

  backend-service:
    build: 
      context: ./backend
    ports:
      - "8888:8888"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/myMernApp
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
